//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staketracker.Core.Res
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Staketracker.Core.Res.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ወደ ሳንድቦክስ ያገናኙ.
        /// </summary>
        public static string connect_to_sandbox
        {
            get
            {
                return ResourceManager.GetString("connect_to_sandbox", resourceCulture);
            }
        }

        public static string dashboard
        {
            get
            {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }

        public static string forgot_your_password
        {
            get
            {
                return ResourceManager.GetString("forgot_your_password", resourceCulture);
            }
        }

        public static string forgot_your_user_id
        {
            get
            {
                return ResourceManager.GetString("forgot_your_user_id", resourceCulture);
            }
        }

        public static string password
        {
            get
            {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        public static string remember_me
        {
            get
            {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }

        public static string sign_in
        {
            get
            {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        public static string user_id
        {
            get
            {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }

        public static string change_language
        {
            get
            {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }

        public static string event_
        {
            get
            {
                return ResourceManager.GetString("event_", resourceCulture);
            }
        }
        public static string communication
        {
            get
            {
                return ResourceManager.GetString("communication", resourceCulture);
            }
        }
        public static string stakeholder
        {
            get
            {
                return ResourceManager.GetString("stakeholder", resourceCulture);
            }
        }
        public static string project_team
        {
            get
            {
                return ResourceManager.GetString("project_team", resourceCulture);
            }
        }
        public static string settings
        {
            get
            {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        public static string sign_out
        {
            get
            {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        public static string help
        {
            get
            {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        public static string topics
        {
            get
            {
                return ResourceManager.GetString("topics", resourceCulture);
            }
        }
        public static string language
        {
            get
            {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        public static string default_interface_language
        {
            get
            {
                return ResourceManager.GetString("default_interface_language", resourceCulture);
            }
        }
        public static string switch_project
        {
            get
            {
                return ResourceManager.GetString("switch_project", resourceCulture);
            }
        }
        public static string change_password
        {
            get
            {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }

        public static string building_form_controls
        {
            get
            {
                return ResourceManager.GetString("building_form_controls", resourceCulture);
            }
        }

        public static string save
        {
            get
            {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        public static string view
        {
            get
            {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        public static string groups
        {
            get
            {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        public static string individuals
        {
            get
            {
                return ResourceManager.GetString("individuals", resourceCulture);
            }
        }
        public static string land_parcels
        {
            get
            {
                return ResourceManager.GetString("land_parcels", resourceCulture);
            }
        }
        public static string commitment_status
        {
            get
            {
                return ResourceManager.GetString("commitment_status", resourceCulture);
            }
        }
        public static string for_the_last_3_months
        {
            get
            {
                return ResourceManager.GetString("for_the_last_3_months", resourceCulture);
            }
        }
        public static string top_5_stakeholder_groups
        {
            get
            {
                return ResourceManager.GetString("top_5_stakeholder_groups", resourceCulture);
            }
        }
        public static string issues_status
        {
            get
            {
                return ResourceManager.GetString("issues_status", resourceCulture);
            }
        }

        public static string by_entry_date
        {
            get
            {
                return ResourceManager.GetString("by_entry_date", resourceCulture);
            }
        }
        public static string add_new
        {
            get
            {
                return ResourceManager.GetString("add_new", resourceCulture);
            }
        }
        public static string edit
        {
            get
            {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        public static string signing_in
        {
            get
            {
                return ResourceManager.GetString("signing_in", resourceCulture);
            }
        }

        public static string top_10_topics_discussed
        {
            get
            {
                return ResourceManager.GetString("top_10_topics_discussed", resourceCulture);
            }
        }

        public static string new_password
        {
            get
            {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }

        public static string confirm_password
        {
            get
            {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }

        public static string business_unit
        {
            get
            {
                return ResourceManager.GetString("business_unit", resourceCulture);
            }
        }
        public static string open
        {
            get
            {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }

        public static string project
        {
            get
            {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }

        public static string old_password
        {
            get
            {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        public static string delete
        {
            get
            {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }

        public static string loading_pages
        {
            get
            {
                return ResourceManager.GetString("loading_pages", resourceCulture);
            }
        }




        public static string error_saving
        {
            get
            {
                return ResourceManager.GetString("error_saving", resourceCulture);
            }
        }
        public static string loading
        {
            get
            {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        public static string msg_err_getting_form_fields
        {
            get
            {
                return ResourceManager.GetString("msg_err_getting_form_fields", resourceCulture);
            }
        }

        public static string api_response_error
        {
            get
            {
                return ResourceManager.GetString("api_response_error", resourceCulture);
            }
        }

        public static string ok
        {
            get
            {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        public static string saved
        {
            get
            {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }

        public static string no
        {
            get
            {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        public static string yes
        {
            get
            {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }

        public static string delete_event
        {
            get
            {
                return ResourceManager.GetString("delete_event", resourceCulture);
            }
        }

        public static string msg_delete_confirm
        {
            get
            {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }

        public static string error
        {
            get
            {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }




        public static string saved_successfully
        {
            get
            {
                return ResourceManager.GetString("saved_successfully", resourceCulture);
            }
        }

        public static string msg_error_while_saving
        {
            get
            {
                return ResourceManager.GetString("msg_error_while_saving", resourceCulture);
            }
        }

        public static string msg_error_while_assigning_ui
        {
            get
            {
                return ResourceManager.GetString("msg_error_while_assigning_ui", resourceCulture);
            }
        }

        public static string msg_check_internet_conn
        {
            get
            {
                return ResourceManager.GetString("msg_check_internet_conn", resourceCulture);
            }
        }

        public static string all_rights_reserved
        {
            get
            {
                return ResourceManager.GetString("all_rights_reserved", resourceCulture);
            }
        }

        public static string privacy
        {
            get
            {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }



        public static string password_required
        {
            get
            {
                return ResourceManager.GetString("password_required", resourceCulture);
            }
        }

        public static string user_id_required
        {
            get
            {
                return ResourceManager.GetString("user_id_required", resourceCulture);
            }
        }












        public static string api_error_trying_to_change_pw
        {
            get
            {
                return ResourceManager.GetString("api_error_trying_to_change_pw", resourceCulture);
            }
        }

        public static string password_changed
        {
            get
            {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }

        public static string password_changed_successfully
        {
            get
            {
                return ResourceManager.GetString("password_changed_successfully", resourceCulture);
            }
        }

        public static string is2_enabled_error
        {
            get
            {
                return ResourceManager.GetString("is2_enabled_error", resourceCulture);
            }
        }

        public static string under_development
        {
            get
            {
                return ResourceManager.GetString("under_development", resourceCulture);
            }
        }


        public static string validation_error
        {
            get
            {
                return ResourceManager.GetString("validation_error", resourceCulture);
            }
        }



        public static string incorrect_username_or_password
        {
            get
            {
                return ResourceManager.GetString("incorrect_username_or_password", resourceCulture);
            }
        }

        public static string error_changing_pw
        {
            get
            {
                return ResourceManager.GetString("error_changing_pw", resourceCulture);
            }
        }


        public static string please_try_again
        {
            get
            {
                return ResourceManager.GetString("please_try_again", resourceCulture);
            }
        }
        public static string server_response_error
        {
            get
            {
                return ResourceManager.GetString("server_response_error", resourceCulture);
            }
        }

        public static string issues
        {
            get
            {
                return ResourceManager.GetString("issues", resourceCulture);
            }
        }


        public static string request_your_user_id
        {
            get
            {
                return ResourceManager.GetString("request_your_user_id", resourceCulture);
            }
        }
        public static string email
        {
            get
            {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        public static string request_your_password
        {
            get
            {
                return ResourceManager.GetString("request_your_password", resourceCulture);
            }
        }
        public static string submit
        {
            get
            {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }

    }
}
