//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staketracker.Core.Res
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Staketracker.Core.Res.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ወደ ሳንድቦክስ ያገናኙ.
        /// </summary>
        public static string connect_to_sandbox
        {
            get
            {
                return ResourceManager.GetString("connect_to_sandbox", resourceCulture);
            }
        }

        public static string dashboard
        {
            get
            {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }

        public static string forgot_your_password
        {
            get
            {
                return ResourceManager.GetString("forgot_your_password", resourceCulture);
            }
        }

        public static string forgot_your_user_id
        {
            get
            {
                return ResourceManager.GetString("forgot_your_user_id", resourceCulture);
            }
        }

        public static string password
        {
            get
            {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        public static string remember_me
        {
            get
            {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }

        public static string sign_in
        {
            get
            {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        public static string user_id
        {
            get
            {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }

        public static string change_language
        {
            get
            {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }

        public static string event_
        {
            get
            {
                return ResourceManager.GetString("event_", resourceCulture);
            }
        }
        public static string communication
        {
            get
            {
                return ResourceManager.GetString("communication", resourceCulture);
            }
        }
        public static string stakeholder
        {
            get
            {
                return ResourceManager.GetString("stakeholder", resourceCulture);
            }
        }
        public static string project_team
        {
            get
            {
                return ResourceManager.GetString("project_team", resourceCulture);
            }
        }
        public static string settings
        {
            get
            {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        public static string sign_out
        {
            get
            {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        public static string help
        {
            get
            {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        public static string topics
        {
            get
            {
                return ResourceManager.GetString("topics", resourceCulture);
            }
        }

    }
}
